# Generated by Django 6.0.3 on 2026-07-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='per unit', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('organizer_name', models.CharField(blank=True, max_length=200)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('organizer_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
                ('is_public', models.BooleanField(default=False)),
                ('booking_open', models.BooleanField(default=False)),
                ('max_stalls_per_exhibitor', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Durban', max_length=100)),
                ('province', models.CharField(default='KwaZulu-Natal', max_length=100)),
                ('width_meters', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('length_meters', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='floor_plans/')),
                ('scale_factor', models.FloatField(default=4.0, help_text='Pixels per meter')),
                ('calibration_x1', models.FloatField(default=0)),
                ('calibration_y1', models.FloatField(default=0)),
                ('calibration_x2', models.FloatField(default=0)),
                ('calibration_y2', models.FloatField(default=0)),
                ('calibration_distance_meters', models.FloatField(default=0)),
                ('walkways_json', models.TextField(blank=True)),
                ('exit_markers_json', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.venue'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('exhibition', 'Exhibition Area'), ('food', 'Food Court'), ('entertainment', 'Entertainment'), ('service', 'Service Area'), ('entrance', 'Entrance/Exit'), ('restroom', 'Restrooms'), ('aisle', 'Aisle (Non-bookable)'), ('parking', 'Parking')], default='exhibition', max_length=20)),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('is_bookable', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='events.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stall_prefix', models.CharField(default='S', help_text='Prefix for numbering (S, F, E)', max_length=10)),
                ('position_x', models.IntegerField(default=0, help_text='X position in pixels on floor plan')),
                ('position_y', models.IntegerField(default=0, help_text='Y position in pixels on floor plan')),
                ('width', models.IntegerField(default=100, help_text='Width in pixels on floor plan')),
                ('height', models.IntegerField(default=100, help_text='Height in pixels on floor plan')),
                ('size_sqm', models.DecimalField(decimal_places=2, default=9.0, max_digits=6)),
                ('base_price', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('corner_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('has_water', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('is_corner', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('max_electricity_amps', models.IntegerField(default=15, help_text='Max amps available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='events.event')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalls', to='events.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
