# Generated by Django 6.0.3 on 2026-07-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'verbose_name': 'Floor Plan', 'verbose_name_plural': 'Floor Plans'},
        ),
        migrations.AddField(
            model_name='floorplan',
            name='hall_height_meters',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='hall_width_meters',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='original_height',
            field=models.IntegerField(default=900, help_text='Original canvas height in pixels'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='original_width',
            field=models.IntegerField(default=1600, help_text='Original canvas width in pixels'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='walkway_width_meters',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stall',
            name='build_instructions',
            field=models.TextField(blank=True, help_text='Stand builder instructions for this stall position'),
        ),
        migrations.AddField(
            model_name='stall',
            name='electrical_instructions',
            field=models.TextField(blank=True, help_text='Electrician instructions for this stall position'),
        ),
        migrations.AddField(
            model_name='stall',
            name='entrance_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stall',
            name='is_near_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stall',
            name='num_chairs',
            field=models.PositiveIntegerField(default=2, help_text='Chairs included with this stall'),
        ),
        migrations.AddField(
            model_name='stall',
            name='num_tables',
            field=models.PositiveIntegerField(default=1, help_text='Tables included with this stall'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='scale_factor',
            field=models.FloatField(default=40.0, help_text='Pixels per meter'),
        ),
    ]
