# Generated by Django 6.0.3 on 2026-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_floorplan_options_floorplan_hall_height_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='grid_spacing_px',
            field=models.IntegerField(default=20, help_text='Editor grid spacing in pixels'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='snap_to_grid_px',
            field=models.IntegerField(default=20, help_text='Snap increment in pixels (set equal to grid_spacing_px for 1-grid snap)'),
        ),
    ]
