# Generated by Django 6.0.3 on 2026-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_floorplan_grid_spacing_px_floorplan_snap_to_grid_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='height',
            field=models.IntegerField(default=3000, help_text='Height in mm on floor plan'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='position_x',
            field=models.IntegerField(default=0, help_text='X position in mm on floor plan'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Y position in mm on floor plan'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_prefix',
            field=models.CharField(default='Stand', help_text='Prefix for numbering (Stand, Food, Kiddies)', max_length=10),
        ),
        migrations.AlterField(
            model_name='stall',
            name='width',
            field=models.IntegerField(default=3000, help_text='Width in mm on floor plan'),
        ),
        migrations.AlterUniqueTogether(
            name='stall',
            unique_together={('event', 'name')},
        ),
    ]
