# Generated by Django 6.0.3 on 2026-08-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_stall_height_alter_stall_position_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_image', models.ImageField(upload_to='floor_plan_sections/')),
                ('original_pdf', models.FileField(blank=True, null=True, upload_to='floor_plan_pdfs/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('original_width', models.IntegerField(default=1600, help_text='Image width in pixels')),
                ('original_height', models.IntegerField(default=900, help_text='Image height in pixels')),
                ('hall_width_meters', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('hall_height_meters', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('scale_factor', models.FloatField(default=40.0, help_text='Pixels per meter')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_sections', to='events.event')),
            ],
            options={
                'verbose_name': 'Floor Plan Section',
                'verbose_name_plural': 'Floor Plan Sections',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stall',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalls', to='events.floorplansection'),
        ),
    ]
