# Generated by Django 6.0.3 on 2026-08-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_floorplansection_stall_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stall',
            unique_together={('section', 'name')},
        ),
    ]
