# Generated by Django 6.0.3 on 2026-08-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_stall_unique_per_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation in degrees (0, 90, 180, 270)'),
        ),
    ]
