# Generated by Django 6.0.3 on 2026-08-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_stall_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplansection',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plan_sections/'),
        ),
    ]
