# Generated by Django 6.0.3 on 2026-08-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_floorplansection_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='electricity_deposit',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Electricity deposit per stall requiring power', max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='VAT rate as percentage (e.g. 15.00 for 15%)', max_digits=5),
        ),
    ]
