# Generated by Django 6.0.3 on 2026-09-10 20:08

from django.db import migrations, models


ELECTRICAL_NAMES = [
    'Electrical Connection (15A)',
    'Electrical Connection (30A)',
    'Electrical Connection (60A)',
    'Additional Lighting',
    'Water Connection',
]


def set_categories(apps, schema_editor):
    AccessoryType = apps.get_model('events', 'AccessoryType')
    AccessoryType.objects.filter(name__in=ELECTRICAL_NAMES).update(category='electrical')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_electricity_deposit_event_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorytype',
            name='category',
            field=models.CharField(choices=[('stand', 'Stand Build'), ('electrical', 'Electrical')], default='stand', help_text='Which provider tab this accessory belongs to (Stand Build or Electrical)', max_length=20),
        ),
        migrations.RunPython(set_categories, migrations.RunPython.noop),
    ]
