# Generated by Django 6.0.3 on 2026-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_accessorytype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT rate as percentage (0 — NPO does not charge VAT)', max_digits=5),
        ),
    ]
