# Generated by Django 6.0.3 on 2026-07-07 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit Note'), ('debit', 'Debit Note')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed (invoice)', max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid (payment)', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='bookings.booking')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='invoices.payment')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
