# Generated by Django 6.0.3 on 2026-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_ledgerentry_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT')], default='eft', max_length=20),
        ),
    ]
