# Generated by Django 6.0.3 on 2026-07-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash')], default='eft', max_length=20),
        ),
    ]
