# Generated by Django 6.0.3 on 2026-08-31 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_discountrequest_rejected_at_and_more'),
        ('events', '0008_alter_floorplansection_section_image'),
        ('invoices', '0005_debtdeclaration_debtpaymentschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='events.event'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Primary booking for backward compatibility; use invoice_lines for all stalls', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Reference booking for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Stall description shown on the invoice', max_length=255)),
                ('amount_excl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_incl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line', to='bookings.booking')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
