# Generated by Django 6.0.3 on 2026-10-09 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_recompute_25_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date the payment was made (drives early-payment discount eligibility)'),
        ),
    ]
