# Generated by Django 6.0.3 on 2026-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed discount amount (stand price x percent)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_approved_by',
            field=models.CharField(blank=True, help_text='Who approved the discount (free text)', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_date',
            field=models.DateField(blank=True, help_text='Date the discount was applied', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_motivation',
            field=models.TextField(blank=True, help_text='Motivation for the discount (optional)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual discount percentage applied to the total stand price', max_digits=5),
        ),
    ]
