# Generated by Django 6.0.3 on 2026-07-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('sole', 'Sole Proprietor'), ('ptyltd', 'PTY LTD'), ('cc', 'Close Corporation'), ('other', 'Other')], default='ptyltd', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('catering', 'Catering'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('stand_builder', 'Stand Builder'), ('electrical', 'Electrical'), ('audio_visual', 'Audio/Visual'), ('logistics', 'Logistics'), ('other', 'Other')], default='other', max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField()),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_registers', to='events.event')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_registers', to='providers.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotations', to='events.event')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='providers.serviceprovider')),
            ],
        ),
    ]
