# Generated by Django 6.0.3 on 2026-07-09 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_floorplan_options_floorplan_hall_height_meters_and_more'),
        ('providers', '0002_serviceprovider_alternative_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Category code (e.g., 72140000)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RFQ Category',
                'verbose_name_plural': 'RFQ Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=30, unique=True)),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter / executive summary')),
                ('methodology', models.TextField(blank=True, help_text='Technical approach and methodology')),
                ('total_amount_excl', models.DecimalField(decimal_places=2, help_text='Total quoted amount (excl VAT)', max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_incl', models.DecimalField(decimal_places=2, help_text='Total quoted amount (incl VAT)', max_digits=12)),
                ('payment_terms', models.CharField(blank=True, help_text='Proposed payment terms', max_length=200)),
                ('validity_period', models.CharField(blank=True, help_text='Validity of quotation (e.g., 30 days)', max_length=100)),
                ('delivery_timeline', models.CharField(blank=True, help_text='Proposed delivery / completion timeline', max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='ERP internal evaluation notes')),
                ('submitted_by_provider', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotations', to='providers.serviceprovider')),
            ],
            options={
                'ordering': ['rfq', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='quotation_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.quotation')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Detailed scope of work / requirements')),
                ('deliverables', models.TextField(blank=True, help_text='Expected deliverables / outputs')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Procurement terms, conditions, and evaluation criteria')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Submissions'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(help_text='Deadline for proposal submissions')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget range', max_digits=12, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Procurement contact', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('site_visit_required', models.BooleanField(default=False)),
                ('site_visit_date', models.DateTimeField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, help_text='Supporting documents / terms of reference', null=True, upload_to='rfq_documents/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='events.event')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='providers.rfqcategory')),
            ],
            options={
                'verbose_name': 'Request for Proposal',
                'verbose_name_plural': 'Requests for Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='providers.rfq'),
        ),
        migrations.CreateModel(
            name='QuotationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_order', models.IntegerField(help_text='1=First Director, 2=Second Director')),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_approvals', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='providers.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Approval',
                'verbose_name_plural': 'Quotation Approvals',
                'unique_together': {('quotation', 'approval_order')},
            },
        ),
    ]
