# Generated by Django 6.0.3 on 2026-07-09 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_rfqcategory_quotation_quotationdocument_rfq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='submitter_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_company_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitter_vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_quotations', to='providers.serviceprovider'),
        ),
    ]
