# Generated by Django 6.0.3 on 2026-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_quotation_submitter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='site_meeting_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled site meeting date/time', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force password change on next login'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('acceptable', 'Accepted Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
    ]
