# Generated by Django 6.0.3 on 2026-09-10 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_discountrequest_rejected_at_and_more'),
        ('providers', '0005_quotation_site_meeting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking', 'New Booking'), ('accessory', 'New Accessory'), ('requirements', 'Requirements Updated'), ('system', 'System')], default='booking', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_notifications', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='providers.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
