# Generated by Django 6.0.3 on 2026-09-10 21:13

from django.db import migrations
from django.contrib.auth.hashers import make_password


def set_ashley_login(apps, schema_editor):
    ServiceProvider = apps.get_model('providers', 'ServiceProvider')
    p = ServiceProvider.objects.filter(email='mogalia.apps@gmail.com').first()
    if p:
        p.password = make_password('ash123')
        p.must_change_password = False
        p.save(update_fields=['password', 'must_change_password'])


def unset_ashley_login(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_providernotification'),
    ]

    operations = [
        migrations.RunPython(set_ashley_login, unset_ashley_login),
    ]
