# Generated by Django 6.0.3 on 2026-09-10 21:18

from django.db import migrations


def rename_ashley_email(apps, schema_editor):
    ServiceProvider = apps.get_model('providers', 'ServiceProvider')
    ServiceProvider.objects.filter(email='mogalia.apps@gmail.com').update(email='ashmunitz@gmail.com')


def reverse_rename(apps, schema_editor):
    ServiceProvider = apps.get_model('providers', 'ServiceProvider')
    ServiceProvider.objects.filter(email='ashmunitz@gmail.com').update(email='mogalia.apps@gmail.com')


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_ashley_stand_builder_login'),
    ]

    operations = [
        migrations.RunPython(rename_ashley_email, reverse_rename),
    ]
