# Generated by Django 6.0.3 on 2026-07-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0002_ledgerentry_receipt'),
        ('providers', '0005_quotation_site_meeting_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FNBAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FNB Access Token',
                'verbose_name_plural': 'FNB Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FNBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('branch_code', models.CharField(default='250655', max_length=10)),
                ('bic', models.CharField(default='FIRNZAJJ', max_length=11)),
                ('account_type', models.CharField(choices=[('debtor', 'Business Account (Debtor)'), ('creditor', 'Beneficiary Account (Creditor)')], max_length=20)),
                ('account_holder', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, help_text='Internal label', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['account_type', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='FNBPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to FNB'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('fnb_response', models.JSONField(blank=True, null=True)),
                ('fnb_request_id', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_payments', to='fnb_integration.fnbaccount')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_payments', to='fnb_integration.fnbaccount')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_payments', to='providers.expense')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_payments', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'FNB Payment Record',
                'verbose_name_plural': 'FNB Payment Records',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='FNBTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fnb_integration.fnbaccount')),
            ],
            options={
                'verbose_name': 'FNB Transaction',
                'verbose_name_plural': 'FNB Transactions',
                'ordering': ['-transaction_date'],
                'unique_together': {('account', 'transaction_date', 'description', 'debit_amount', 'credit_amount')},
            },
        ),
    ]
