# Generated by Django 6.0.3 on 2026-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnbtransaction',
            name='mapped_to',
            field=models.CharField(blank=True, help_text='Auto-mapped invoice/expense reference', max_length=200, null=True),
        ),
    ]
