# Generated by Django 6.0.3 on 2026-07-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('exhibitor', 'Exhibitor'), ('staff', 'Staff'), ('director', 'Director'), ('finance', 'Finance'), ('service_provider', 'Service Provider'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='exhibitor', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'unique_together': {('role', 'section')},
            },
        ),
    ]
