# Generated by Django 6.0.3 on 2026-07-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_user_user_type_user_role_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('rfq', 'RFQ / Procurement'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30),
        ),
    ]
