# Generated by Django 6.0.3 on 2026-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_of_address',
            field=models.FileField(blank=True, help_text='Proof of address (PDF, JPG, PNG)', upload_to='proof_of_address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
