# Generated by Django 6.0.3 on 2026-08-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_proof_of_address_user_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport-style photo of the exhibitor', upload_to='exhibitor_photos/'),
        ),
    ]
