# Generated by Django 6.0.3 on 2026-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_reg_number',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT number (if VAT registered)', max_length=50),
        ),
    ]
