# Generated by Django 6.0.3 on 2026-08-30 23:37

from django.db import migrations, models


def backfill_new_sections(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    mapping = [
        ('accounting', 'gate_takings'),
        ('invoices', 'debt_declarations'),
    ]
    for parent, child in mapping:
        for parent_perm in RolePermission.objects.filter(section=parent):
            RolePermission.objects.update_or_create(
                role=parent_perm.role,
                section=child,
                defaults={
                    'can_view': parent_perm.can_view,
                    'can_create': parent_perm.can_create,
                    'can_edit': parent_perm.can_edit,
                    'can_delete': parent_perm.can_delete,
                },
            )


def remove_new_sections(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    RolePermission.objects.filter(section__in=['gate_takings', 'debt_declarations']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_company_reg_number_user_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('gate_takings', 'Daily Gate Takings'), ('debt_declarations', 'Debt Declarations'), ('rfq', 'RFQ / Procurement'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30),
        ),
        migrations.RunPython(backfill_new_sections, remove_new_sections),
    ]
