# Generated by Django 6.0.3 on 2026-08-30 23:47

from django.db import migrations, models


def backfill_booking_reports(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    for parent_perm in RolePermission.objects.filter(section='reports'):
        RolePermission.objects.update_or_create(
            role=parent_perm.role,
            section='booking_reports',
            defaults={
                'can_view': parent_perm.can_view,
                'can_create': parent_perm.can_create,
                'can_edit': parent_perm.can_edit,
                'can_delete': parent_perm.can_delete,
            },
        )


def remove_booking_reports(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    RolePermission.objects.filter(section='booking_reports').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('gate_takings', 'Daily Gate Takings'), ('debt_declarations', 'Debt Declarations'), ('rfq', 'RFQ / Procurement'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('booking_reports', 'Consolidated Bookings Reports'), ('users', 'User Management')], max_length=30),
        ),
        migrations.RunPython(backfill_booking_reports, remove_booking_reports),
    ]
