# Generated by Django 6.0.3 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sa_id_passport',
            field=models.CharField(blank=True, help_text='SA ID / Passport number', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_reg_number',
            field=models.CharField(blank=True, help_text='Company registration number (optional)', max_length=50),
        ),
    ]
