# Generated by Django 6.0.3 on 2026-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_sa_id_passport_alter_user_company_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sa_id_passport_copy',
            field=models.FileField(blank=True, help_text='Copy of SA ID / Passport (PDF, JPG, PNG)', upload_to='sa_id_copies/'),
        ),
    ]
