# Generated by Django 6.0.3 on 2026-10-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_sa_id_passport_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('gate_takings', 'Daily Gate Takings'), ('debt_declarations', 'Debt Declarations'), ('rfq', 'RFQ / Procurement'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('booking_reports', 'Consolidated Bookings Reports'), ('users', 'User Management'), ('stall_changes', 'Stand Changes'), ('refunds', 'Refunds'), ('early_discounts', 'Early Discounts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('exhibitor', 'Exhibitor'), ('staff', 'Staff'), ('director', 'Director'), ('organiser', 'Organiser'), ('finance', 'Finance'), ('service_provider', 'Service Provider'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='exhibitor', max_length=20),
        ),
    ]
