# Generated by Django 6.0.3 on 2026-10-08 18:55

from django.db import migrations, models


def backfill_payment_reports(apps, schema_editor):
    """Grant the new Payment Status Report permission to every role that can
    already see the consolidated booking reports (same access as before)."""
    RolePermission = apps.get_model('accounts', 'RolePermission')
    for parent_perm in RolePermission.objects.filter(section='booking_reports'):
        RolePermission.objects.update_or_create(
            role=parent_perm.role,
            section='payment_reports',
            defaults={
                'can_view': parent_perm.can_view,
                'can_create': parent_perm.can_create,
                'can_edit': parent_perm.can_edit,
                'can_delete': parent_perm.can_delete,
            },
        )


def remove_payment_reports(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    RolePermission.objects.filter(section='payment_reports').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_new_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events'), ('floor_plan', 'Floor Plan'), ('bookings', 'Bookings'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('exhibitors', 'Exhibitors'), ('providers', 'Service Providers'), ('expenses', 'Expenses'), ('gate_takings', 'Daily Gate Takings'), ('debt_declarations', 'Debt Declarations'), ('rfq', 'RFQ / Procurement'), ('accounting', 'Accounting'), ('reports', 'Reports'), ('booking_reports', 'Consolidated Bookings Reports'), ('payment_reports', 'Payment Status Report'), ('users', 'User Management'), ('stall_changes', 'Stand Changes'), ('refunds', 'Refunds'), ('early_discounts', 'Early Discounts')], max_length=30),
        ),
        migrations.RunPython(backfill_payment_reports, remove_payment_reports),
    ]
