# Generated by Django 6.0.3 on 2026-07-07 16:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed (Paid)'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit', 'Deposit Paid'), ('partial', 'Partially Paid'), ('paid', 'Paid in Full')], default='unpaid', max_length=20)),
                ('stall_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessories_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_deposit', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fascia_name', models.CharField(blank=True, help_text='Name on fascia board (max 28 chars)', max_length=28)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('requires_power', models.BooleanField(default=False)),
                ('power_amps', models.IntegerField(default=0, help_text='Additional power required in amps')),
                ('requires_water', models.BooleanField(default=False)),
                ('require_stand_build', models.BooleanField(default=False)),
                ('require_remove_side_walls', models.BooleanField(default=False)),
                ('require_floor_mat', models.BooleanField(default=False)),
                ('require_carpet', models.BooleanField(default=False)),
                ('special_requirements', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.stall')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.accessorytype')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved_by_first', 'Approved by First Admin'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('approved_by_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='bookings.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
