# Generated by Django 6.0.3 on 2026-07-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exhibitor_requirements',
            field=models.TextField(blank=True, help_text="Exhibitor's special requirements"),
        ),
        migrations.AddField(
            model_name='booking',
            name='require_additional_power_amps',
            field=models.IntegerField(default=0, help_text='Additional power amps (15 or 30)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='require_extra_lights',
            field=models.BooleanField(default=False, help_text='Extra lighting required'),
        ),
        migrations.AddField(
            model_name='booking',
            name='require_extra_plugs',
            field=models.BooleanField(default=False, help_text='Extra power plugs required'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stand_build_instructions',
            field=models.TextField(blank=True, help_text='Special stand build instructions'),
        ),
    ]
