# Generated by Django 6.0.3 on 2026-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_exhibitor_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='electrical_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements_version',
            field=models.IntegerField(default=0, help_text='Incremented when exhibitor changes requirements'),
        ),
        migrations.AddField(
            model_name='booking',
            name='side_wall_removal',
            field=models.CharField(choices=[('none', 'None'), ('left', 'Remove Left'), ('right', 'Remove Right'), ('both', 'Remove Both')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='stand_build_completed',
            field=models.BooleanField(default=False),
        ),
    ]
