# Generated by Django 6.0.3 on 2026-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_discountrequest_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='electrical_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stand_build_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
