# Generated by Django 6.0.3 on 2026-09-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_electrical_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='products_description',
            field=models.TextField(blank=True, help_text='Description of products to be sold or promoted'),
        ),
    ]
