# Generated by Django 6.0.3 on 2026-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='early_payment_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Early full-payment discount on stand price', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='early_payment_tier',
            field=models.CharField(blank=True, help_text='5 or 2.5', max_length=10),
        ),
    ]
