# Generated by Django 6.0.3 on 2026-07-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking Update'), ('payment', 'Payment Received'), ('invoice', 'Invoice'), ('discount', 'Discount Request'), ('reminder', 'Payment Reminder'), ('rfq', 'RFQ / Proposal'), ('system', 'System')], max_length=20),
        ),
    ]
